# Generated by Django 3.0.8 on 2020-07-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoybeanCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_ending', models.DateField()),
                ('condition', models.CharField(choices=[('Very Poor', 'Very Poor'), ('Poor', 'Poor'), ('Fair', 'Fair')], max_length=30)),
                ('average_temperature', models.DecimalField(decimal_places=3, max_digits=3)),
                ('grade', models.IntegerField()),
                ('inspector', models.CharField(max_length=50)),
            ],
        ),
    ]
